### PR TITLE
Deploy from av-* branches

### PR DESCRIPTION
**Pull request by andreabolognani**
@phoracek the Travis CI configuration fix I promised :)

### CODE REVIEW

**Comment by phoracek** [comment]
Don't we need to adjust deploy.sh? It will push :latest from all branches. So if we rebuild av-8.0, it would appear as newer than 8.2.

If we don't care, I'm fine with this. The branch name should be indirectly reflected in the image tag thanks to `COPR_VERSION` variable.

**Comment by andreabolognani** [comment]
> Don't we need to adjust deploy.sh? It will push :latest from all branches. So if we rebuild av-8.0, it would appear as newer than 8.2.

Having a `latest` tag at all for these container images was a mistake, exactly for the reason you mention. I intend to remove that completely, as well make some other minor adjustments.

> If we don't care, I'm fine with this. The branch name should be indirectly reflected in the image tag thanks to COPR_VERSION variable.

We haven't cared until now, so I think it's fine to merge this right away to get an av-8.2 build done and then get rid of the `latest` tag as a follow-up.

@rmohr, does that sound reasonable to you?

**Review by phoracek — APPROVED** [review]

**Comment by rmohr** [comment]
No one uses `latest`. Fine to proceed in my opinion.

**Comment by andreabolognani** [comment]
@phoracek the new image (av-8.2-20200514-cc2bc34) has been built.

**Comment by phoracek** [comment]
Thanks @andreabolognani 

I'm bumping the version in kubevirt, but I have one concern. We both pull this base-image there and download libvirt libs and sources (to support libvirt Go package AFAIK). Those RPMs are now outdated. Is not this mismatch putting us in risk?

https://github.com/kubevirt/kubevirt/blob/master/WORKSPACE#L69

**Comment by andreabolognani** [comment]
> I'm bumping the version in kubevirt, but I have one concern. We both pull this base-image there and download libvirt libs and sources (to support libvirt Go package AFAIK). Those RPMs are now outdated. Is not this mismatch putting us in risk?

I don't quite understand what's going on there, sorry. As a general concept, it would certainly be good to have the very same RPMs used everywhere.

**Pull request merged**
