### PR TITLE
Use upstream releases for libvirt and QEMU

### PR DESCRIPTION
**Pull request by andreabolognani**
We've been discussing about doing this for a very long time, and here it is :)

* [test build](https://travis-ci.org/github/andreabolognani/kubevirt-libvirt/builds/730941771)
* [resulting container image](https://hub.docker.com/layers/andreabolognani/kubevirt-libvirt/20200928-95d3026/images/sha256-12e95f396684876c84f2eb4c1a99a5fe7076b438dffa2b246d2b72473151884c)

The PR looks quite massive, but that's just because I start off by merging back `av-8.2` into `master`. The actual changes are fairly small and straightforward.

I moved everything back to `master` because, with one COPR per package build, it doesn't really make sense to have named branches by default: if we later find ourselves in a situation where we need to backport fixes to a certain version of KubeVirt after it's been released, we can simply create a `v0.xx` branch off the commit that was used to create the corresponding container image.

### CODE REVIEW

**Comment by andreabolognani** [comment]
@rmohr It looks like kubevirt-bot doesn't like the way I've approached the pre-changes merge. If merging `av-8.2` back into `master` this way looks reasonable to you, perhaps I could go ahead and just push those commits directly, reducing this PR to a single commit?

**Comment by crobinso** [comment]
The final commit that adds the actual changes LGTM. I pulled your container and used it to run the kubevirt migration test suite locally and things passed.

If things are choking on the master merge, maybe add a new branch with the new changes for now, and we deal with master branch separately?

**Comment by andreabolognani** [comment]
> If things are choking on the master merge, maybe add a new branch with the new changes for now, and we deal with master branch separately?

The merge itself is fine I think, it's just that the automation is not prepared to deal with merges.

Using a separate branch would also not improve things if we agree that ultimately we want to develop on the master branch, it would just push the problem further into the future and possibly make the resulting merge even messier as a consequence. Plus I would never create a new branch without @rmohr's thumbs-up anyway :)

IMHO the most reasonable solution is to push the merge manually and then rebase this PR on top of the resulting master branch.

**Comment by rmohr** [comment]
@andreabolognani I think the only issue is that the merge contained commits which are not dco signed. Or do I miss something?

**Comment by rmohr** [comment]
@andreabolognani maybe you want to rebase on the branch to pick up #59

**Comment by andreabolognani** [comment]
> @andreabolognani I think the only issue is that the merge contained commits which are not dco signed. Or do I miss something?

Lack of DCO in merge commits is the main one, but there's also this bit:

> Keywords which can automatically close issues and at(@) mentions are not allowed in commit messages.
>
> The list of commits with invalid commit messages:
>
> * ed8892d Fixes #42, Fixes #25

Not sure whether you can override that too.

> @andreabolognani maybe you want to rebase on the branch to pick up #59

Definitely! I'm going to do it right now :)

**Comment by rmohr** [comment]
> Lack of DCO in merge commits is the main one, but there's also this bit:
> 
> >

Ah ok, see it now. We can ignore them. We just recently enabled this prow plugin. It helps to avoid that such things ever get in. If they are already in and you have them in your PR, it will complain. So after we merge this one the problem should not exist for new PRs.

**Comment by andreabolognani** [comment]
> Ah ok, see it now. We can ignore them. We just recently enabled this prow plugin. It helps to avoid that such things ever get in. If they are already in and you have them in your PR, it will complain. So after we merge this one the problem should not exist for new PRs.

Good to know, it was just not clear to me whether the PR could be merged despite those checks failing.

I have rebased to pick up Cole's recent changes and also simplified the code a bit while I was at it :)

**Comment by rmohr** [comment]
> Good to know, it was just not clear to me whether the PR could be merged despite those checks failing.

Yes manual merges (which are the only ones here anyway) will always work. We just try to avoid the keywords in commit messages, because they have funny side-effects, since when such commit gets moved around they can close issues, spam people with emails and so on.

**Comment by andreabolognani** [comment]
@rmohr Apologies for pestering you but I'm still unclear on how to move forward with this... We're using the vanilla GitHub merge functionality for this repo and so it looks like the DCO check failure is not actually stopping us from going ahead with the merge: the corresponding button in the web UI is enabled. So, should I just go ahead with that? Do the changes - the merge itself, plus the follow-up adjustment - look reasonable to you? Thanks!

**Comment by rmohr** [comment]
> @rmohr Apologies for pestering you but I'm still unclear on how to move forward with this... We're using the vanilla GitHub merge functionality for this repo and so it looks like the DCO check failure is not actually stopping us from going ahead with the merge: the corresponding button in the web UI is enabled. So, should I just go ahead with that? Do the changes - the merge itself, plus the follow-up adjustment - look reasonable to you? Thanks!

Sure just go ahead. Sorry for the confusion. Tide is not enabled for merging in this repo. We just enabled the `dco` check across the whole org, so that people have insight into that. That is a requirement for being part of the CNCF.

**Comment by andreabolognani** [comment]
Great, I'll go ahead then! Thanks :)

**Pull request merged**
