### PR TITLE
Update to libvirt 5.6.0

### PR DESCRIPTION
**Pull request by rmohr**
In order to keek kubevit working with libvirt 5.6.0, the following modifications were necessary:

 * install iptables explicitly, since it does not seem to be part of the minimal installation anymore
 * set `rmember_users` to `0`, in order to avoid that libvirt tries to write `XATTRS` on the containerfilesystems.
 * install libvirt-daemon-driver-storage-core for minimal storage support (required for instance during migrations)

### CODE REVIEW

**Comment by rmohr** [comment]
@andreabolognani I created a av-8.0 branch and want to move to libvirt 5.6 from fedora 31 with this, until we have the copr repos ready, to unblock kubevirt/kubevirt master. Could you have a look?

**Comment by rmohr** [comment]
kubevirt passes all test on https://github.com/kubevirt/kubevirt/pull/2893

**Review by stu-gott — APPROVED** [review]

**Comment by andreabolognani** [comment]
> @andreabolognani I created a av-8.0 branch and want to move to libvirt 5.6 from fedora 31 with this, until we have the copr repos ready, to unblock kubevirt/kubevirt master. Could you have a look?

Sorry for not replying right away.

Overall the changes look sensible to me; there are a couple minor things that warrant follow-up changes, and I've posted https://github.com/kubevirt/libvirt/pull/40 to take care of those.

The remaining issue is the fact that we had to disable `ppc64le` due to build issues on the architectures... I haven't had time to look into it, but from the error message reported in https://github.com/kubevirt/libvirt/commit/1b63a2e84baacbb270d84f2f96c4bf12080b3996 I think addressing it might be just a matter of adding `SLOF` to the COPRs.

@crobinso, what do you think?

**Comment by andreabolognani** [comment]
Oh, and it goes without saying that if we later want `aarch64`, or even just EFI support on `x86_64`, then we should add `edk2` as well... There's a bunch more packages in the `virt-preview` COPR, but aside from these two I'm not sure which ones might be relevant to KubeVirt.

**Comment by crobinso** [comment]
I think the ppc64 dep issues should be fixed in av-8.0, I dropped the SLOF version locking and submitted a new build yesterday. If you are still hitting issue let me know

Re: adding SLOF. I suspect for kubevirt's needs, using fedora SLOF and edk2 should be okay, patches are generally in sync. Also I'm trying to limit the time I spend on maintaining these repos, so unless there's a really compelling reason I'd prefer not to add them.

But for the next version of repos provided by the virt packaging team, it makes sense for them to supply the entire RHEL virt module for consumption, which should cover all the dependent roms.

**Comment by andreabolognani** [comment]
> I think the ppc64 dep issues should be fixed in av-8.0, I dropped the SLOF version locking and submitted a new build yesterday. If you are still hitting issue let me know
> 
> Re: adding SLOF. I suspect for kubevirt's needs, using fedora SLOF and edk2 should be okay, patches are generally in sync.

Yeah, that seems to work fine. As mentioned above I didn't really investigate the issue, and so I mistakenly assumed it was caused by SLOF being missing altogether rather than simply not meeting QEMU's requirements :)

> Also I'm trying to limit the time I spend on maintaining these repos, so unless there's a really compelling reason I'd prefer not to add them.
> 
> But for the next version of repos provided by the virt packaging team, it makes sense for them to supply the entire RHEL virt module for consumption, which should cover all the dependent roms.

Fair enough. As far as I can tell, the current selection of packages with the current tweaks is enough to test against both AV 8.0 and AV 8.1, so we should be all set (modulo the occasional sync, which I assume doesn't take too much time) for the time being. Thanks for all the work you've done!

**Pull request merged**
