### PR TITLE
Install all virt-launcher dependencies in the libvirt image

### PR DESCRIPTION
**Pull request by rmohr**
Bazel does not allow RUN commands, make sure that all dependencies are
already there.

Signed-off-by: Roman Mohr <rmohr@redhat.com>

### CODE REVIEW

**Comment by fabiand** [comment]
Could you explain this change a little more?

**Comment by rmohr** [comment]
Oh, sorry, did not want to open a pr yet.

**Comment by fabiand** [comment]
Alright, fair enough :) I just wondered about the ctx

**Comment by rmohr** [comment]
The context is, that in order to speed up CI and development and make it more robust, we need an extra docker registry where we can push to. That involves "insecure" registries, which require manual docker daemon configurations. Bazel can build/push/pull docker containers without docker and does not have the limitations regarding to insecure registries. However it does not support "RUN". I am experimenting with that.

**Comment by rmohr** [comment]
and it also supports reproducible docker builds ...

**Pull request closed without merging**
