### PR TITLE
Add more build types

### PR DESCRIPTION
**Pull request by andreabolognani**
This takes most of the commits prepared by @crobinso for #58 (with some slight tweaks) and goes further by implementing some of the ideas I had already [written about](https://github.com/kubevirt/libvirt/pull/58#pullrequestreview-508593724) in that context.

The code is not particularly pretty but hey, it gets the job done.

Test CI run, including the deployment part: https://travis-ci.org/github/andreabolognani/kubevirt-libvirt/builds/744488653

### CODE REVIEW

**Review by crobinso — APPROVED** [review]
Looks good to me and fits my needs, thanks for taking care of this.

May be overkill if this repo is going to die after Roman's bazeldnf changes, but it's useful in the interim.

FYI *.inc.sh is not a pattern I see in kubevirt repo, but `common.sh` naming is used in kubevirt and kubevirt-ci.

**Comment by andreabolognani** [comment]
> FYI *.inc.sh is not a pattern I see in kubevirt repo, but `common.sh` naming is used in kubevirt and kubevirt-ci.

Thanks for the heads-up, changed now.

**Comment by andreabolognani** [comment]
@rmohr are you okay merging this?

**Comment by rmohr** [comment]
I made cole an admin. If you two agree that this is fine, that is good enough for me. :+1:

**Comment by andreabolognani** [comment]
Cool! I'll go ahead then :)

**Pull request merged**
