### PR TITLE
Add CONTRIBUTING.md 

### PR DESCRIPTION
**Pull request by agowa**
This is a copy of https://raw.githubusercontent.com/kubevirt/kubevirt/master/CONTRIBUTING.md,
I'd like to add it to this repo in order to fix the 'contributing guide'-link kubevirt-bot posts.

Signed-off-by: Klaus Frank <git@frank.fyi>

### CODE REVIEW

**Comment by andreabolognani** [comment]
If you import the file directly, the copy and the original will naturally get out of sync over time.

I think a better approach is to have a much shorter file in `kubevirt/libvirt` that merely points to the main, up to date one in `kubevirt/kubevirt`: this is the approach [kubevirt/project-infra has taken](https://github.com/kubevirt/project-infra/blob/master/CONTRIBUTING.md), and I think we should replicate it here.

Can you respin in that direction? And when you do, can you please make sure you target this at the `av-8.2` branch? Thanks!

**Comment by andreabolognani** [comment]
@agowa338 much better :)

Can you please wrap the text at 80 column and squash the two commits together? No point in adding a bunch of text only to remove it in the very next commit...

Thanks!

**Comment by agowa** [comment]
Done, I thought it would be easier to review. I'm used to the github squash merge feature ;-)

**Comment by andreabolognani** [comment]
> Done, I thought it would be easier to review. I'm used to the github squash merge feature ;-)

Maybe the problem is that I am _not_ used to it :)

Anyway, the squash looks good but you didn't wrap the contents so that lines don't exceed 80 columns... Can you do that please?

**Comment by agowa** [comment]
Well, I did, but I did not run `git rebase --continue`...

**Comment by andreabolognani** [comment]
Merged, thanks!

**Pull request merged**
