### PR TITLE
Add support for ppc64le

### PR DESCRIPTION
**Pull request by nitkon**
Add ppc64le Dockerfile and amend travis to run
on ppc64le arch as well.

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
lgtm, in the future we also can configure to pass Docker credentials to publish image automatically
@rmohr If you do not have objections I want to merge this PR.

**Review by cynepco3hahue — APPROVED** [review]

**Comment by rmohr** [comment]
> lgtm, in the future we also can configure to pass Docker credentials to publish image automatically

@cynepco3hahue I think it will publish the image. `deploy.sh` is the same for both I  think. Let's see.

**Review by rmohr — APPROVED** [review]
lgtm. :+1:

**Comment by rmohr** [comment]
Btw. would it be possible to use the tech preview repo also for ppc, or is that only available for amd64?

**Pull request merged**
